settings:
  docker:
    replicate_local_python_environment: "pip_freeze"
    apt_packages:
      - git
  orchestrator.local_docker:
      run_args:
        network_mode: "host"
      memory: 8
steps:
  new_svc_trainer:
    settings:
      orchestrator.local_docker:
        cpus: 8
model:
  name: iris_classifier

enable_cache: False


parameters:
    gamma: 0.01